# render.yaml
services:
  # Backend API
  - type: web
    name: funcionarios-api
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: fdbfias
          property: connectionString
    healthCheckPath: /api/health
    autoDeploy: true

  # Base de datos PostgreSQL
  - type: pgsql
    name: dbfias
    plan: starter
    ipAllowList: []
    databaseName: dbfias
    user: dbfias_user
databases:
  - name: dbfias
    databaseName: dbfias
    plan: starter
