services:
  - type: web
    name: funcionarios-api
    env: node
    region: us-east
    buildCommand: yarn install --frozen-lockfile && yarn build
    startCommand: yarn start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: NODE_VERSION
        value: 20.11.1
      - key: YARN_VERSION
        value: 1.22.22
    healthCheckPath: /api/health
    autoDeploy: true
